import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NFT Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-5">
        <h1 className="text-3xl font-bold">NFT Game</h1>
      </main>
    </div>
  );
};

export default Home;
