import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Header } from "../components/common";

import Form from "../components/form";
import Web3React from "../components/web3-react";
import { useDemoContext } from "../context/demo-context";
// import Image from "next/image";

const Home: NextPage = () => {
  const { todos, saveTodo } = useDemoContext();
  console.log(todos, saveTodo);

  return (
    <>
      <Head>
        <title>NFT Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="m-5">
        <h1 className="text-3xl font-bold">NFT Game</h1>
        <Web3React />
        {/* <Form  /> */}
      </main>
    </>
  );
};

export default Home;
